In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

创建一个四维数组，并且求最后两维的和

In [5]:
arr1 = np.random.randint(0,10,size=(2,3,4,5))  

In [12]:
arr1


array([[[[6, 7, 8, 3, 2],
         [5, 0, 7, 9, 5],
         [4, 3, 8, 3, 0],
         [3, 0, 4, 8, 9]],

        [[0, 5, 1, 5, 2],
         [9, 1, 7, 3, 9],
         [9, 9, 5, 5, 6],
         [2, 6, 9, 6, 2]],

        [[1, 2, 2, 3, 9],
         [5, 8, 1, 5, 0],
         [0, 1, 7, 9, 7],
         [1, 9, 9, 5, 9]]],


       [[[5, 3, 6, 5, 8],
         [9, 7, 1, 9, 7],
         [5, 2, 2, 8, 9],
         [1, 8, 3, 2, 4]],

        [[9, 5, 2, 4, 5],
         [5, 3, 8, 5, 4],
         [1, 5, 9, 2, 9],
         [2, 5, 6, 5, 0]],

        [[5, 0, 5, 4, 4],
         [2, 5, 9, 6, 1],
         [5, 3, 7, 4, 5],
         [6, 6, 9, 3, 0]]]])

In [11]:
sum = np.sum(arr1,axis=(2,3))
sum

array([[ 94, 101,  93],
       [104,  94,  89]])

In [20]:
arr2 = np.array([[6, 7, 8, 3, 2],
         [5, 0, 7, 9, 5],
         [4, 3, 8, 3, 0],
         [3, 0, 4, 8, 9]])
np.sum(arr2)

94

给定一个数组[1,2,3,4] ,在每一个元素后边加上三个0

In [21]:
arr3 = np.arange(1,5)
arr3


array([1, 2, 3, 4])

In [24]:
arr4 = np.zeros(16,dtype=np.int16)
arr4

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [27]:
arr4[::4] = arr3
arr4

array([1, 2, 3, 4], dtype=int16)